name: ➕ Add to Prism
description: Submit a request to have something added to the Prism Libraries
title: "[Add]: "
labels: "Add"
assignees:
  - KeirAnsell
body:
  - type: markdown
    attributes:
      value: "### ⚠️ Please select the relevant platform for your request by selecting the relevant label on the right."
  - type: markdown
    attributes:
       value: "If necessary, select the High Priority label and requests marked as such will take a priority over others."
  - type: textarea
    id: summary
    attributes:
      label: 🗒️ Summary
      description: A clear description of what you would like added to the Prism Libraries and why/an example use case.
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: 🖼️ Screenshot
      description: Please include a screenshot of the component or components that you are submitting.
      placeholder: Click the field before dragging the screenshot in.
    validations:
      required: false
  - type: textarea
    id: attachments
    attributes:
      label: 📎 Attachments
      description: Please include either a zipped Sketch document, or a link to a Sketch Document containing the component(s) that you are submitting..
      placeholder: Click the field before dragging a file in.
    validations:
      required: false
  - type: dropdown
    id: live
    attributes:
      label: 🌐 Is this change live?
      description: Is this addition live in our apps yet?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: 🔢 If not...
      description: which version will this go live with?
      multiple: false
      options:
        - 88
        - 89
        - 90
        - 91
        - 92
        - 93
        - 94
        - 95
        - 96
        - 97
        - 98
        - 99
        - 100
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Include any other relevant information about the request here.
