name: Update Carat Presentation
description: Requeste or Suggest to have a new Slide layout added to the Carat Presentation Library.
title: "[Presentation]: "
labels: "Presentation"
assignees:
  - KeirAnsell
body:
  - type: markdown
    attributes:
       value: "If you would like to request a new Slide or modifications to an existing Slide, please complete and submit the form below."
  - type: textarea
    id: summary
    attributes:
      label: 🗒️ Summary
      description: Please describe the Slide Layout that you would like to be added.
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: 🖼️ Screenshot
      description: If possible, please include a rough mockup of the Layout of the Slide.
      placeholder: Click the field before dragging the screenshot in.
    validations:
      required: false
  - type: textarea
    id: attachments
    attributes:
      label: 📎 Attachments
      description: If you have found a similar example or have mocked anything up that you would like to include, please include it here.
      placeholder: Click the field before dragging a file in.
    validations:
      required: false
  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Include any other relevant information about the request here.
